/*
 * generated by Xtext 2.10.0
 */
package br.ufpe.cin.dsoa.ide


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class DsoaStandaloneSetup extends DsoaStandaloneSetupGenerated {

	def static void doSetup() {
		new DsoaStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
