/*
 * generated by Xtext 2.10.0
 */
package br.ufpe.cin.dsoa.ide


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class DsoaRuntimeModule extends AbstractDsoaRuntimeModule {
}
